// Trendy Shopping Point - Product Catalog Data
const initialProducts = [
  // --- PENS ---
  {
    id: "pen-01",
    name: "Luxury Matte Metal Rollerball Pen",
    category: "pen",
    categoryLabel: "Pens",
    price: 199,
    originalPrice: 299,
    rating: 4.8,
    reviewsCount: 42,
    badge: "Bestseller",
    description: "Premium smooth-writing metal body rollerball pen with German black ink refill. Perfect for daily office work and signatures.",
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Smooth 0.5mm Tip", "Refillable Metal Body", "Smudge-Free Quick Dry Ink"]
  },
  {
    id: "pen-02",
    name: "Trendy Pastel Gel Pen Set (Pack of 6)",
    category: "pen",
    categoryLabel: "Pens",
    price: 149,
    originalPrice: 199,
    rating: 4.9,
    reviewsCount: 88,
    badge: "Trending",
    description: "Aesthetic pastel barrel gel pens with ultra-smooth 0.5mm tip. Ideal for journaling, notes, and school projects.",
    image: "https://images.unsplash.com/photo-1569683795645-b62e50fbf103?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Soft Grip", "Pastel Aesthetic Casing", "Waterproof Black/Blue Ink"]
  },
  {
    id: "pen-03",
    name: "Classic Fountain Pen with Converter",
    category: "pen",
    categoryLabel: "Pens",
    price: 349,
    originalPrice: 499,
    rating: 4.7,
    reviewsCount: 29,
    badge: "Premium",
    description: "Elegant fine nib fountain pen with brass accents and ink cartridge converter for timeless writing experience.",
    image: "https://images.unsplash.com/photo-1585336261026-77cc7c20c029?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Stainless Steel Iridium Nib", "Smooth Ink Flow", "Gift Box Included"]
  },

  // --- PENCILS ---
  {
    id: "pencil-01",
    name: "Professional Art & Sketching Pencil Set (12 Grades)",
    category: "pencil",
    categoryLabel: "Pencils",
    price: 249,
    originalPrice: 350,
    rating: 4.9,
    reviewsCount: 64,
    badge: "Top Choice",
    description: "Graphite drawing pencils from 2H to 8B for shading, architectural sketches, and creative illustrations.",
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Break-Resistant Lead", "Grades from 2H to 8B", "Non-Toxic Cedar Wood"]
  },
  {
    id: "pencil-02",
    name: "Aesthetic Metallic Mechanical Pencil 0.7mm",
    category: "pencil",
    categoryLabel: "Pencils",
    price: 99,
    originalPrice: 150,
    rating: 4.6,
    reviewsCount: 51,
    badge: "Sale",
    description: "Ergonomic click mechanical pencil with cushioned rubber grip and built-in eraser with extra refill leads.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["0.7mm Hi-Polymer Lead", "Retractable Sleeve", "Non-Slip Textured Grip"]
  },
  {
    id: "pencil-03",
    name: "Vibrant Watercolor Colored Pencils (24 Shades)",
    category: "pencil",
    categoryLabel: "Pencils",
    price: 399,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 73,
    badge: "Creative",
    description: "Soft core blendable colored pencils that can be transformed into watercolor art with a wet brush.",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Water-Soluble", "Rich Pigmentation", "Pre-Sharpened"]
  },
  {
    id: "pencil-apsara",
    name: "Apsara Pencil - Pack of 10 (HB Grade)",
    category: "pencil",
    categoryLabel: "Pencils",
    price: 30,
    originalPrice: 40,
    rating: 4.8,
    reviewsCount: 210,
    badge: "Popular",
    description: "Apsara HB pencils are India's most trusted school pencil brand. Smooth, consistent graphite with a strong break-resistant lead. Perfect for everyday school writing and light sketching.",
    image: "https://m.media-amazon.com/images/I/71nPfnpq1RL._SL1500_.jpg",
    inStock: true,
    features: ["HB Grade Lead", "Break-Resistant Core", "Pack of 10", "Smooth Writing"]
  },
  {
    id: "pencil-natraj",
    name: "Natraj Pencil - Pack of 10 (HB Grade)",
    category: "pencil",
    categoryLabel: "Pencils",
    price: 25,
    originalPrice: 35,
    rating: 4.7,
    reviewsCount: 185,
    badge: "Bestseller",
    description: "Natraj HB pencils – a classic choice for students and professionals alike. Excellent value for money with reliable graphite quality and easy sharpening. A staple in every school bag.",
    image: "https://m.media-amazon.com/images/I/61L8wgdIo5L._SL1500_.jpg",
    inStock: true,
    features: ["HB Grade", "Easy to Sharpen", "Pack of 10", "Durable Cedar Wood"]
  },

  // --- SLIPPERS ---
  {
    id: "slipper-01",
    name: "Cloud Cushion Ultra-Soft Slide Slippers",
    category: "slipper",
    categoryLabel: "Slippers",
    price: 399,
    originalPrice: 699,
    rating: 4.9,
    reviewsCount: 112,
    badge: "Popular",
    description: "Super light, 4cm thick EVA platform sole slides for all-day comfort, anti-slip indoor and outdoor daily wear.",
    image: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Thick 4cm Cushioning", "Waterproof & Quick Dry", "Ergonomic Arch Support"]
  },
  {
    id: "slipper-02",
    name: "Memory Foam Cozy Indoor House Slippers",
    category: "slipper",
    categoryLabel: "Slippers",
    price: 499,
    originalPrice: 799,
    rating: 4.8,
    reviewsCount: 84,
    badge: "Cozy",
    description: "Plush breathable lining with high-density memory foam insole and rubber anti-skid bottom for maximum warmth & relaxation.",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Breathable Cotton Fleece", "Dual Layer Memory Foam", "Quiet Rubber Sole"]
  },
  {
    id: "slipper-03",
    name: "Trendy Casual Daily Wear Flip-Flops",
    category: "slipper",
    categoryLabel: "Slippers",
    price: 249,
    originalPrice: 399,
    rating: 4.6,
    reviewsCount: 95,
    badge: "Budget Buy",
    description: "Durable, flexible rubber strap beach and casual flip-flops designed for long-lasting comfort and grip.",
    image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Flexible Rubber Base", "Anti-Chafing Straps", "Shock Absorbing"]
  },

  // --- BAGS ---
  {
    id: "bag-01",
    name: "Trendy Smart College & Laptop Backpack",
    category: "bag",
    categoryLabel: "Bags",
    price: 899,
    originalPrice: 1499,
    rating: 4.9,
    reviewsCount: 154,
    badge: "Hot Deal",
    description: "Water-resistant 30L spacious backpack with padded 15.6-inch laptop compartment, USB charging port, and anti-theft zipper.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Water-Resistant Fabric", "Padded Laptop Slot (15.6\")", "USB Port & Multi Pockets"]
  },
  {
    id: "bag-02",
    name: "Aesthetic Canvas Tote Bag with Zipper",
    category: "bag",
    categoryLabel: "Bags",
    price: 349,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 78,
    badge: "Trending",
    description: "Heavy-duty 100% organic cotton canvas tote bag with inner pocket and secure zipper closure. Perfect for shopping & college.",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Sturdy Reinforced Handles", "Inner Zipper Pocket", "Eco-Friendly Canvas"]
  },
  {
    id: "bag-03",
    name: "Compact Crossbody Travel Sling Bag",
    category: "bag",
    categoryLabel: "Bags",
    price: 499,
    originalPrice: 799,
    rating: 4.7,
    reviewsCount: 61,
    badge: "Compact",
    description: "Multifunctional lightweight chest and crossbody shoulder sling bag for keys, phone, wallet, and travel essentials.",
    image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Adjustable Shoulder Strap", "Waterproof Nylon", "Hidden Back Pocket"]
  },

  // --- FANCIES & ACCESSORIES ---
  {
    id: "fancy-01",
    name: "Korean Pearl & Crystal Hair Claw Clips (Pack of 4)",
    category: "fancies",
    categoryLabel: "Fancies",
    price: 199,
    originalPrice: 349,
    rating: 4.9,
    reviewsCount: 120,
    badge: "Trendy",
    description: "Exquisite high-grade acrylic and pearl embellished hair claw clips with strong spring grip for all hair types.",
    image: "https://images.unsplash.com/photo-1535295972055-1c762f4483e5?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Strong Spring Hold", "Glossy Pearl Finish", "Pack of 4 Designs"]
  },
  {
    id: "fancy-02",
    name: "Cute 3D Silicone Animal Keychains with Strap",
    category: "fancies",
    categoryLabel: "Fancies",
    price: 129,
    originalPrice: 199,
    rating: 4.8,
    reviewsCount: 89,
    badge: "Gift Item",
    description: "High quality premium silicone 3D cartoon figurine keychains with woven wristlet and gold-tone metal hook.",
    image: "https://images.unsplash.com/photo-1614036417651-efe5912149d8?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Soft Touch Silicone", "Sturdy Metal Clasp", "Vibrant Colors"]
  },
  {
    id: "fancy-03",
    name: "Aesthetic LED Digital Watch & Fashion Bracelet Combo",
    category: "fancies",
    categoryLabel: "Fancies",
    price: 299,
    originalPrice: 499,
    rating: 4.7,
    reviewsCount: 94,
    badge: "Combo Deal",
    description: "Minimalist touch-screen LED digital watch paired with an adjustable layered charm bracelet.",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Touch LED Display", "Adjustable Fit", "Complimentary Bracelet"]
  },
  {
    id: "fancy-04",
    name: "Trendy Aesthetic Stickers & Washi Tape Gift Box",
    category: "fancies",
    categoryLabel: "Fancies",
    price: 249,
    originalPrice: 399,
    rating: 4.9,
    reviewsCount: 67,
    badge: "Best Gift",
    description: "Delightful box containing 10 rolls of patterned washi tapes and 25 waterproof vinyl stickers for decoration and scrapbooking.",
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    features: ["Residue-Free Peel", "Gold Foil Accents", "Deluxe Storage Box"]
  }
];
